services:
  frontend:
    image: ghcr.io/benjamin-wheeler00/cs4273capstone/frontend:main
    ports:
      - "3000"
  backend:
    image: ghcr.io/benjamin-wheeler00/cs4273capstone/backend:main
    gpus: all
    #ports:
    #  - "5001"
  ollama:
    image: ghcr.io/benjamin-wheeler00/cs4273capstone/ollama:main
    gpus: all
    #ports:
    #  - "11434"
    #environment:
    #  OLLAMA_IGPU_ENABLE: 1
    #devices:
    #  - "/dev/dri"
